GROUND = ' '
WALL = '☼'
DEAD = 'Ѡ'


CONSTRUCTION = '╬'
CONSTRUCTION_DESTROYED_DOWN = '╩'
CONSTRUCTION_DESTROYED_UP = '╦'
CONSTRUCTION_DESTROYED_LEFT = '╠'
CONSTRUCTION_DESTROYED_RIGHT = '╣'
CONSTRUCTION_DESTROYED_DOWN_TWICE = '╨'
CONSTRUCTION_DESTROYED_UP_TWICE = '╥'
CONSTRUCTION_DESTROYED_LEFT_TWICE = '╞'
CONSTRUCTION_DESTROYED_RIGHT_TWICE = '╡'
CONSTRUCTION_DESTROYED_LEFT_RIGHT = '│'
CONSTRUCTION_DESTROYED_UP_DOWN = '─'
CONSTRUCTION_DESTROYED_UP_LEFT = '┌'
CONSTRUCTION_DESTROYED_RIGHT_UP = '┐'
CONSTRUCTION_DESTROYED_DOWN_LEFT = '└'
CONSTRUCTION_DESTROYED_DOWN_RIGHT = '┘'

CONSTRUCTIONS = (
    CONSTRUCTION,
    CONSTRUCTION_DESTROYED_DOWN,
    CONSTRUCTION_DESTROYED_UP,
    CONSTRUCTION_DESTROYED_LEFT,
    CONSTRUCTION_DESTROYED_RIGHT,
    CONSTRUCTION_DESTROYED_DOWN_TWICE,
    CONSTRUCTION_DESTROYED_UP_TWICE,
    CONSTRUCTION_DESTROYED_LEFT_TWICE,
    CONSTRUCTION_DESTROYED_RIGHT_TWICE,
    CONSTRUCTION_DESTROYED_LEFT_RIGHT,
    CONSTRUCTION_DESTROYED_UP_DOWN,
    CONSTRUCTION_DESTROYED_UP_LEFT,
    CONSTRUCTION_DESTROYED_RIGHT_UP,
    CONSTRUCTION_DESTROYED_DOWN_LEFT,
    CONSTRUCTION_DESTROYED_DOWN_RIGHT,
)

SHOTS_TO_DESTROY = {
    CONSTRUCTION: 3,
    CONSTRUCTION_DESTROYED_DOWN: 2,
    CONSTRUCTION_DESTROYED_UP: 2,
    CONSTRUCTION_DESTROYED_LEFT: 2,
    CONSTRUCTION_DESTROYED_RIGHT: 2,
    CONSTRUCTION_DESTROYED_DOWN_TWICE: 1,
    CONSTRUCTION_DESTROYED_UP_TWICE: 1,
    CONSTRUCTION_DESTROYED_LEFT_TWICE: 1,
    CONSTRUCTION_DESTROYED_RIGHT_TWICE: 1,
    CONSTRUCTION_DESTROYED_LEFT_RIGHT: 1,
    CONSTRUCTION_DESTROYED_UP_DOWN: 1,
    CONSTRUCTION_DESTROYED_UP_LEFT: 1,
    CONSTRUCTION_DESTROYED_RIGHT_UP: 1,
    CONSTRUCTION_DESTROYED_DOWN_LEFT: 1,
    CONSTRUCTION_DESTROYED_DOWN_RIGHT: 1,
}

BARRIERS = CONSTRUCTIONS + (WALL, )

BULLET = '•'

# UP, DOWN, LEFT, RIGHT = "UP", "DOWN", "LEFT", "RIGHT"
# MOVES = (UP, RIGHT, DOWN, LEFT)

TANK_UP = '▲'
TANK_RIGHT = '►'
TANK_DOWN = '▼'
TANK_LEFT = '◄'
SELF_TANKS = (TANK_UP, TANK_RIGHT, TANK_DOWN, TANK_LEFT)


OTHER_TANK_UP = '˄'
OTHER_TANK_RIGHT = '˃'
OTHER_TANK_DOWN = '˅'
OTHER_TANK_LEFT = '˂'
OTHER_TANKS = (OTHER_TANK_UP, OTHER_TANK_RIGHT, OTHER_TANK_DOWN, OTHER_TANK_LEFT)

AI_TANK_UP = '?'
AI_TANK_RIGHT = '»'
AI_TANK_DOWN = '¿'
AI_TANK_LEFT = '«'
AI_TANKS = (AI_TANK_UP, AI_TANK_RIGHT, AI_TANK_DOWN, AI_TANK_LEFT)

ENEMIES = OTHER_TANKS + AI_TANKS

VEC_UP = [-1, 0]
VEC_DOWN = [1, 0]
VEC_RIGHT = [0, 1]
VEC_LEFT = [0, -1]

TANK_TO_VEC = {TANK_UP: VEC_UP,
               TANK_DOWN: VEC_DOWN,
               TANK_RIGHT: VEC_RIGHT,
               TANK_LEFT: VEC_LEFT,}

# TANK_TO_MOVE = {TANK_UP: UP,
#                 TANK_DOWN: DOWN,
#                 TANK_RIGHT: RIGHT,
#                 TANK_LEFT: LEFT,}
#
# MOVE_TO_VEC = {UP: VEC_UP,
#                DOWN: VEC_DOWN,
#                RIGHT: VEC_RIGHT,
#                LEFT: VEC_LEFT,}
